### ISSUE TITLE
is_ascii_whitespace undefined

### ISSUE THREAD

**Issue by alexaandru** [euclidianAce/tree-sitter-teal#25]
Hello,

After the recent changes, I can no longer use the parser. Is it just me? 

I can see `is_ascii_whitespace` being referenced here https://github.com/euclidianAce/tree-sitter-teal/blob/main/src/scanner.c#L204 and https://github.com/euclidianAce/tree-sitter-teal/blob/main/src/scanner.c#L213 however I cannot find a definition for it. When trying to use the parser I get:

```
scanner.c: In function ‘tree_sitter_teal_external_scanner_scan’:
scanner.c:204:12: warning: implicit declaration of function ‘is_ascii_whitespace’; did you mean ‘is_whitespace’? [-Wimplicit-function-declaration]
  204 |     while (is_ascii_whitespace(lexer->lookahead))
      |            ^~~~~~~~~~~~~~~~~~~
      |            is_whitespace
```

**Comment by euclidianAce** [comment]
This function got renamed due to a bad merge on my part, should be fixed now. Thanks for the report!

**Comment by alexaandru** [comment]
Yup, it's back working! Thank you & you're most welcome :-) Cheers!
